### ISSUE TITLE
Mobile app decimal transactions

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#126]
When I transfer 0,1 coins, i see in the mobile app an amount of 0 transactions as the app does not show amounts behing the comma. I propose to visualize up to 0,01 transactions. 

The same is valid for my account balance, I want to see that i have 12,15 coins and not only 12 coins ;-)

**Comment by gdalyy** [comment]
I've discussed this with @haythem96 and he said that coins amount must be `integer` not `float`, in other words , we can't have 0.5 coin or 0.1 coin or whatever , only integers are possible.

**Comment by KarimChabrak** [comment]
Uups, mean if you sell single bonbons (or taba3 chikley), they will be very expensive.

**Comment by gdalyy** [comment]
@haythem96 , karim is right , we didn't thought about this.

**Comment by KarimChabrak** [comment]
@gdalyy   if this is the case, we can store in the blockchain the transactions of the unit mCOIN. Which means milli Coin and represents 0,001 Coin. 
In the interfaces, we can either visualize  12150 mCCC,    or 12,15 CCC.  As we want. 

As this issue seems needing more work than expected, let's postpone it.   We could eventuall  disable non integer transactions in the coinsence platform as long this issue is not solved.

**Comment by haythem96** [comment]
I didn’t say we can’t have 0.5, you miss understood me

**Comment by gdalyy** [comment]
I thought you said its mandatory to have integers not floats when dealing with coins !

**Comment by haythem96** [comment]
I was talking about the Coin decimal at that time, when the CCC coin got issued, the decimal passed was 0 for some reason (I know u told me u have it as 18 but somewhere in humhub where an issue where it got passed to the APi as 0).

So in Ethereum, if you are using a token with 18 decimal, if you send 1.5 token u are basically sending 1.5*10**18 which is basically a decimal number.

So in our case the decimal is 0, that's why I said we can't transfer a fraction of a token, so if you send 1.5 => 1.5*10**0 = 1.5 => error !

The only solution is to re-deploy the CCC coin => migrate balances & txs again

**Comment by gdalyy** [comment]
Got it , thanks

**Comment by haythem96** [comment]
Fixed this on the mobile app... will work when we deploy (re-migrate) coins.
