### ISSUE TITLE
Create a subdomain for the testing platform

### ISSUE THREAD

**Issue by craxrev** [Coinsence/meta#31]
To make our testing platform accessible easly when demoing changes, we need to make a subdomain for that.
We could add it to one of the reserved domains: 
- testing.coinsence.com
- testing.coinsence.org

**Comment by gdalyy** [comment]
@KarimChabrak , since our main platform is hosted by Humhub team, can you please ask them to create a sudomain for our dev platform, i'll provide them an elastic IP address associated to our AWS EC2 instance so that they can add an A record to the DNS record of  the subdomain. 

For the subdomain, i propose *dev.coinsence.org* since *test.coinsence.org* already exists

**Comment by bumi** [comment]
I think @KarimChabrak you own and control the domain, don't you?

**Comment by KarimChabrak** [comment]
I have the domain. I will check on strato which settings i did make and create a subdomain dev.coinsence.org

**Comment by KarimChabrak** [comment]
Which CNAME-Record shall I set for the subdomain dev.coinsence.org?

**Comment by gdalyy** [comment]
Point it to our public DNS on AWS `ec2-3-16-41-127.us-east-2.compute.amazonaws.com` .

**Comment by gdalyy** [comment]
@KarimChabrak, can you please try with this `18.217.56.153`, it's an `Elastic IP` that i've created through the AWS Dashboard and i've associated to the EC2 instance that holds the dev platform. If it doesn't work , try to create an **A Record** rather than an **CNAME Record**.

**Comment by bumi** [comment]
configured the an A record for the domain to point to the mentioned IP.
