### ISSUE TITLE
Remove creating new account when task is changed

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#32]
a new task account is created when  changing:

- responsible user
- assigned user
- task name

Instead, only the account manager or accont name shall be changed

![image](https://user-images.githubusercontent.com/41925899/52820967-c5f2a600-30ad-11e9-94de-ed5a0e86f5d5.png)

**Comment by KarimChabrak** [comment]
@gdalyy     Account creation when task is created does not work anymore. Please check.

**Comment by gdalyy** [comment]
Did you choose : Associate Account checkbox ?

**Comment by KarimChabrak** [comment]
Now I saw it.

There is a new issue. 
- When you do not directly assign a task responsible, the account has no manager.
- When changing task responsible, the account manager does not change.

**Comment by bumi** [comment]
this is exactly the hidden complexity of such features. (and that list will easily get longer and we will never finish it.) 
and as you see any of such exceptions also makes it more complicate for the users. 

in any case this issue is solved? for the other bugs/features can you create new issues that we can then discuss there.

**Comment by gdalyy** [comment]
@KarimChabrak , I will take a look and see what's going wrong.
@bumi :+1:

**Comment by gdalyy** [comment]
Fixed, @KarimChabrak please check on dev.coinsence.org
