### ISSUE TITLE
Sanitize user input on custom landing pages

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#35]
PR https://github.com/Coinsence/humhub-modules-custom-pages/pull/2 introduced the option to create custom HTML pages. For security reasons we must sanitize the user input through an HTML tag whitelist. 

as discussed in #2 we can use the yii built in sanitizers for that. (content + title)

**Comment by craxrev** [comment]
Another thing should be discussed here, whether the sanitization is done when:
- retrieving HTML from db: before rendering the view, best for our current case (basic HTML), so that when reterning to edit mode, the user can find his untouched code (with unrendered tag).
- sending HTML to db: after adding/editing, ideal when implementing the CKEditor with ACF.

**Comment by bumi** [comment]
what is easiest?
what do you think?

and even in edit mode we should only render sanitized input - otherwise it could still be exploited.

**Comment by craxrev** [comment]
both are the same (code speaking), complexity might differ depending on the best practice of where the filtering code should be. still looking for the best possible way.
the edit mode I'm speaking about is where you put the HTML code, I'm not speaking about CKEditor on that point.

**Comment by bumi** [comment]
so if both works, then I actually add it at least when data is stored. 

(re: edit: if you add malicious code and I edit the page then you can still attack me)

**Comment by craxrev** [comment]
just created a [PR](https://github.com/Coinsence/humhub-modules-custom-pages/pull/3) with a testing commit for the purifier logic, deploying on testing platform..

**Comment by craxrev** [comment]
Deployed on testing.

**Comment by bumi** [comment]
done! \o/
