### ISSUE TITLE
Marketplace add/edit product 

### ISSUE THREAD

**Issue by gdalyy** [Coinsence/meta#65]
As a simple user i would like to be able to add products to the marketplace.

A product has as fields : 
-  product name
-  product simple description
-  product detailed description ( rich text editor )
-  product main picture
-  price ( in requested asset )

**Comment by gdalyy** [comment]
@KarimChabrak can spaces sell products too ?

**Comment by KarimChabrak** [comment]
yes. Spaces can also sell products and services.

**Comment by KarimChabrak** [comment]
Some comments regarding acutal version
*********************************************
- all spaces appear in the selection of payment asset, even if they did not issue coins.

*********************************************
- before price, user shall be able to select OFFER TYPE, with two option "Discount for coins" or "Total price in coin". If user select discout, the he gives discount in percentage, otherwise he give the price.
*********************************************
- Instead of payment type drop down, i would ask user to type a short text 

-- if offer type is discount, ask "please type what is your regular currency e.g. $, €, tnd,... and how much discount you offer per coin"    

--if offer is price per unit, ask "please indicate if the price is e.g. per day, per service, per hour,..."
*********************************************
In the marketplace remove the words "requesting" and "payment"

let simply appear   e.g.  

Discount [20%]  for  [coin symbol]
[3,5 tunisian dinar per coin]

Price [200] [coin symbol]
[per hour]

the second line which is the short text input of the user shall be a smaller text in gray.
*********************************************
We can also remove in the marketplace thr time information (when the offer has bern made)

**Comment by KarimChabrak** [comment]
Some comments regarding acutal version
*********************************************
- all spaces appear in the selection of payment asset, even if they did not issue coins.

*********************************************
- before price, user shall be able to select OFFER TYPE, with two option "Discount for coins" or "Total price in coin". If user select discout, the he gives discount in percentage, otherwise he give the price.
*********************************************
- Instead of payment type drop down, i would ask user to type a short text 

-- if offer type is discount, ask "please type what is your regular currency e.g. $, €, tnd,... and how much discount you offer per coin"    

--if offer is price per unit, ask "please indicate if the price is e.g. per day, per service, per hour,..."
*********************************************
In the marketplace remove the words "requesting" and "payment"

let simply appear   e.g.  

Discount [20%]  for  [coin symbol]
[3,5 tunisian dinar per coin]

Price [200] [coin symbol]
[per hour]

the second line which is the short text input of the user shall be a smaller text in gray.
*********************************************
We can also remove in the marketplace thr time information (when the offer has bern made)

**Comment by KarimChabrak** [comment]
Some comments regarding acutal version
*********************************************
- all spaces appear in the selection of payment asset, even if they did not issue coins.

*********************************************
- before price, user shall be able to select OFFER TYPE, with two option "Discount for coins" or "Total price in coin". If user select discout, the he gives discount in percentage, otherwise he give the price.
*********************************************
- Instead of payment type drop down, i would ask user to type a short text 

-- if offer type is discount, ask "please type what is your regular currency e.g. $, €, tnd,... and how much discount you offer per coin"    

--if offer is price per unit, ask "please indicate if the price is e.g. per day, per service, per hour,..."
*********************************************
In the marketplace remove the words "requesting" and "payment"

let simply appear   e.g.  

Discount [20%]  for  [coin symbol]
[3,5 tunisian dinar per coin]

Price [200] [coin symbol]
[per hour]

the second line which is the short text input of the user shall be a smaller text in gray.
*********************************************
We can also remove in the marketplace thr time information (when the offer has bern made)
