### ISSUE TITLE
Initialize ethereum DAO on space creation 

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#72]
When a user creates a space we need to create the related ethereum DAO. 
We do that through an HTTP API call to our smart contract wrapper. 

HumHub needs to store the DAO ethereum address in the database.

## ToDos:

- [x] HTTP wrapper endpoint
- [x] humhub HTTP call   

## Questions: 

* When do we create the user's ethereum wallet?
* How do we make sure that the creator/owner account has enough funds to pay for the space creation?

related: #70

**Comment by haythem96** [comment]
for the ethereum wallet, I think it will be good to create it when a user create an account in the platform

**Comment by gdalyy** [comment]
Does the creator/owner has to pay in order to create a space ?

**Comment by bumi** [comment]
any ethereum transaction costs money (called GAS). So yes the creator has to pay for that.

**Comment by haythem96** [comment]
I thought about this...let's say we deploy the contracts in Rinkeby, we create a coinsence wallet where we fund this wallet with eth, each time a user create an account we just send him some eth from that wallet...in this case we only need to make sure that the "coinsence" wallet have eth.

I can't find a way to automate the process of a wallet getting some eth from Rinkeby with a script or something... because of the need to publish a post in a social network to get eth....

**Comment by bumi** [comment]
yeah, we should collect some rinkeby ETH for that already.

**Comment by haythem96** [comment]
how much ETH do u think we need ?

**Comment by bumi** [comment]
creating a new DAO is probably expensive... need to check again what it was in gas. but maybe $100 ? 
the rest should be ok. so maybe we fund the accounts for now on testnet with 1-2ETH. we review that once we plan mainnet release.
